Repository UNSEEN-STUDY-GROUP/unreal-engine-study, pull requests merged in 2024-04, with the labels that each got.

#8 우측값 레퍼런스와 이동 생성자
  MinjuCho/Rvalue_Reference_and_Move_Constructor.md
  MinjuCho/image-1.png
  MinjuCho/image-2.png
  MinjuCho/image-3.png
  MinjuCho/image-4.png
  MinjuCho/image-5.png
  MinjuCho/image-6.png
  MinjuCho/image-7.png
  MinjuCho/image.png
Labels: C++

#11 [Feat] 언리얼 엔진의 Actor
  Inyeong/README.md
Labels: Unreal

#13 Docs: Add UnrealEngine TestCode
  Jeonglee/UnrealTestcode.md
Labels: Unreal

#14 [INYEONG] 언리얼의 모듈화 캐릭터
  Inyeong/Actor.md
  Inyeong/ModularCharacter.md
Labels: C++, Unreal

#20 이득우의 언리얼 C++ 게임 개발의 정석 - 캐릭터
  MinjuCho/Unreal5_Project_Player.md
  MinjuCho/image-10.png
  MinjuCho/image-11.png
  MinjuCho/image-12.png
  MinjuCho/image-13.png
  MinjuCho/image-8.png
  MinjuCho/image-9.png
Labels: Unreal

#18 언리얼 멀티플레이 네트워크 복제 이해하기
  Soyeon/img/Untitled 1.png
  Soyeon/img/Untitled 10.png
  Soyeon/img/Untitled 11.png
  Soyeon/img/Untitled 12.png
  Soyeon/img/Untitled 13.png
  Soyeon/img/Untitled 14.png
  Soyeon/img/Untitled 15.png
  Soyeon/img/Untitled 16.png
  Soyeon/img/Untitled 17.png
  Soyeon/img/Untitled 18.png
  Soyeon/img/Untitled 19.png
  Soyeon/img/Untitled 2.png
  Soyeon/img/Untitled 20.png
  Soyeon/img/Untitled 21.png
  Soyeon/img/Untitled 22.png
  Soyeon/img/Untitled 23.png
  Soyeon/img/Untitled 24.png
  Soyeon/img/Untitled 25.png
  Soyeon/img/Untitled 26.png
  Soyeon/img/Untitled 27.png
  Soyeon/img/Untitled 28.png
  Soyeon/img/Untitled 29.png
  Soyeon/img/Untitled 3.png
  Soyeon/img/Untitled 4.png
  Soyeon/img/Untitled 5.png
  Soyeon/img/Untitled 6.png
  Soyeon/img/Untitled 7.png
  Soyeon/img/Untitled 8.png
  Soyeon/img/Untitled 9.png
  Soyeon/img/Untitled.png
  Soyeon/언리얼 멀티플레이 네트워크 복제 이해하기.md
Labels: Unreal

#16 권영민 언리얼 엔진 컨퍼런스 발표 자료
  KwonYeongmin/언리얼 엔진 모듈에서는 UCL을 어떻게 사용할까.md
  KwonYeongmin/언리얼 엔진 분할 화면 R&D.md
Labels: C++, Unreal
